gesdinet_jwt_refresh_token:
    ttl_update: true # Met à jour la durée de vie à chaque utilisation
    user_identity_field: email # Champ utilisateur utilisé comme identifiant
    refresh_token_class: App\Entity\RefreshToken # Classe d'entité utilisée pour les refresh tokens
    firewall: api # Firewall concerné
    cookie:
        enabled: true
        same_site: strict
        path: /
        domain: null
        http_only: true
        secure: true
